!TRANSPOSE OF A MATRIX
PROGRAM TRAN_MAT
 IMPLICIT NONE
 REAL::MAT(100,100),TRAN(100,100)
 INTEGER::I,J,R,C
 PRINT*,"ENTER THE ROW AND COLUMN NUMBERS"
 READ*,R,C
PRINT*,"SO YOUR MATRIX IS",R,"X",C,"MATRIX"
PRINT*,"ENTER THE ELEMENT OF THE MATRIX"
DO I=1,R
 DO J=1,C
  read*,MAT(I,J)
 END DO
END DO
PRINT*,"TRANSPOSE OF THE GIVEN MATRIX:"
DO I=1,C
 PRINT*,(MAT(J,I),J=1,R)
END DO
END PROGRAM TRAN_MAT
